using System.Text.RegularExpressions;

internal sealed record MeaningGolden(string Id, string Original, string[] RequiredPatterns, string[] ExactLiterals,
    string[] ForbiddenPatterns, string[] OrderedMarkers, string UsefulExample, string[] BadExamples,
    string Utility, bool CanStructure = true);

// Independently authored before REFINE-47 implementation. Examples are semantic
// acceptance/rejection witnesses, not expected model strings or implementation mirrors.
internal static class MeaningGoldens
{
    internal static readonly HashSet<string> PriorEightIds = ["reported-poem-exact", "email-no-new-obligations", "poem-rough-grammar", "email-rough-grammar", "explanation-count-and-prohibition", "ordered-actions-negation", "literal-code-preservation", "substantial-rephrase-rough-input"];
    internal static readonly MeaningGolden[] All = [
        new("reported-poem-exact", "Write a poem on a boat sailing in a sea on a lonely night",
            [@"\b(?:write|draft|compose) a poem\b", @"\ba boat sailing in a sea on a lonely night\b"], [],
            [@"\b(stanza|sonnet|rhyme|rhyming|captain|tragic|sad|melanchol\w*|ocean|first.person|third.person|ending|metaphor|while you|aboard)\b"], [],
            "Task: Write a poem.\nSubject: A boat sailing in a sea on a lonely night.",
            ["Write a poem on a boat sailing in a sea on a lonely night.", "Draft a poem on a boat sailing in a sea on a lonely night.",
             "Task: Write a poem on a boat sailing in a sea on a lonely night.",
             "Task: Write a poem.\nScene: a lonely boat sailing in a sea at night.",
             "Task: Write a poem.\nScene: a boat sailing in a sea on a lonely night.\nFormat: 4 rhyming stanzas."],
            "Separate the requested artifact from its source-grounded subject while preserving the complete boat/sailing/sea/lonely-night relation. No fixed poetic form, speaker or new mood."),
        new("email-no-new-obligations", "Write a polite email requesting Friday off.",
            [@"\b(?:write|draft|compose).*\bemail\b", @"\bpolite\b", @"\b(?:requesting|request|asking for) Friday off\b"], [],
            [@"\b(reason|deadline|commitment|manager|medical|appointment|promise|coverage|Monday)\b"], [],
            "Task: Write an email requesting Friday off.\nTone: polite.",
            ["Please draft a polite email requesting Friday off.", "Task: Write a polite email requesting Friday off.\nInclude: a reason and confirmation of no deadline conflicts."],
            "Expose request and supplied tone separately; no invented rationale, recipient, deadline or promise."),
        new("poem-rough-grammar", "Write poem about boat sailing at sea on lonely night.",
            [@"\b(?:write|draft|compose) (?:a )?poem\b", @"\b(?:a )?boat sailing at sea on (?:a )?lonely night\b"], [],
            [@"\b(stanza|sonnet|rhyme|rhyming|captain|tragic|sad|melanchol\w*|ocean|speaker|ending)\b"], [],
            "Task: Write a poem.\nSubject: A boat sailing at sea on a lonely night.",
            ["Write a poem about a boat sailing at sea on a lonely night.", "Task: Write a poem.\nSubject: A lonely boat sailing at sea at night."],
            "Preserve the prior grammar-comparison fixture while requiring useful task/subject structure beyond inserted articles."),
        new("email-rough-grammar", "write polite email asking for Friday off.",
            [@"\b(?:write|draft|compose).*\bemail\b", @"\bpolite\b", @"\b(?:requesting|request|asking for) Friday off\b"], [],
            [@"\b(reason|deadline|commitment|manager|medical|appointment|promise|coverage|Monday)\b"], [],
            "Task: Write an email asking for Friday off.\nTone: polite.",
            ["Please draft a polite email requesting Friday off.", "Task: Write an email asking for Friday off.\nTone: polite.\nInclude: a reason for the request."],
            "Preserve the prior rough-email comparison fixture and separate tone/request without adding obligations."),
        new("ordered-actions-negation", "First summarize report. Then list risks. Do not suggest solutions.",
            [@"\bFirst\b.*\bsummarize (?:the )?report\b", @"\bThen\b.*\blist risks\b", @"\bDo not suggest solutions\b"], [],
            [@"\b(recommend solutions|mitigation|rank risks|top five|executive)\b"], ["First", "Then", "Do not"],
            "Sequence: First summarize the report. Then list risks.\nConstraint: Do not suggest solutions.",
            ["Sequence: First list risks. Then summarize the report.\nConstraint: Do not suggest solutions.", "Task: Summarize the report and suggest solutions.\nOutput: list risks."],
            "Make the sequence and prohibited output independently scannable while retaining explicit order."),
        new("explanation-count-and-prohibition", "Explain difference between RAM and storage in 2 sentences. Do not recommend brands.",
            [@"\bExplain (?:the )?difference between RAM and storage\b", @"\b2 sentences\b", @"\bDo not recommend brands\b"], ["2"],
            [@"\b(two sentences|buy|purchase|examples|table|benchmark)\b"], [],
            "Task: Explain the difference between RAM and storage.\nOutput: 2 sentences.\nConstraint: Do not recommend brands.",
            ["Task: Explain the difference between RAM and storage.\nOutput: two sentences.\nConstraint: Do not recommend brands.", "Task: Explain the difference between RAM and storage.\nOutput: 2 sentences with brand recommendations."],
            "Separate topic, exact numeric format and prohibition without changing any constraint."),
        new("literal-code-preservation", "Explain purpose of `cache_size=64` in one sentence. Do not change `cache_size=64`.",
            [@"\bExplain (?:the )?purpose of `cache_size=64`", @"\bone sentence\b", @"\bDo not change `cache_size=64`"], ["`cache_size=64`"],
            [@"\b(optimize|increase|decrease|bytes|kilobytes|64-bit|performance guarantee)\b"], [],
            "Task: Explain the purpose of `cache_size=64`.\nOutput: one sentence.\nConstraint: Do not change `cache_size=64`.",
            ["Task: Explain the purpose of `cache_size=128`.\nOutput: one sentence.\nConstraint: Do not change `cache_size=128`.", "Task: Optimize `cache_size=64`.\nOutput: one sentence."],
            "Separate explanation, output limit and exact code prohibition; do not infer the unit or behavior of an unknown setting."),
        new("substantial-rephrase-rough-input", "please can you help me to write instructions that explain how to rename a file in Windows. use simple words.",
            [@"\b(?:write|draft|provide) instructions\b", @"\b(?:how to )?rename a file in Windows\b", @"\bsimple words\b"], [],
            [@"\b(Windows 11|Windows 10|PowerShell|terminal|administrator|keyboard shortcut|screenshot|three steps)\b"], [],
            "Task: Write instructions explaining how to rename a file in Windows.\nStyle: Use simple words.",
            ["Please can you help me to write instructions that explain how to rename a file in Windows. Use simple words.", "Task: Write instructions explaining how to rename a file in Windows 11.\nStyle: Use simple words."],
            "Remove conversational scaffolding and expose the task/style without choosing an unstated Windows version or method."),
        new("conditional-scope", "Compare A and B only if both are available; otherwise ask which is missing. Do not guess.",
            [@"Compare A and B only if both are available", @"otherwise ask which is missing", @"Do not guess"], [],
            [@"\b(assume|estimate missing|default values|if either)\b"], [],
            "Task and condition: Compare A and B only if both are available; otherwise ask which is missing.\nConstraint: Do not guess.",
            ["Task: Compare A and B if either is available.\nFallback: Ask which is missing.\nConstraint: Do not guess.", "Task: Compare A and B.\nCondition: Only ask which is missing if both are available.\nConstraint: Do not guess."],
            "Expose the prohibition while preserving the entire conditional relation and fallback scope."),
        new("fact-number-bindings", "Compare April revenue of $12,500 with May revenue of $10,000; list April first. Do not calculate tax.",
            [@"April revenue of \$12,500", @"May revenue of \$10,000", @"list April first", @"Do not calculate tax"], ["$12,500", "$10,000"],
            [@"\b(profit|growth rate|tax rate|forecast|USD|2026)\b"], [],
            "Task: Compare April revenue of $12,500 with May revenue of $10,000.\nOrder: list April first.\nConstraint: Do not calculate tax.",
            ["Task: Compare April revenue of $10,000 with May revenue of $12,500.\nOrder: list April first.\nConstraint: Do not calculate tax."],
            "Separate comparison facts, presentation order and excluded calculation without swapping value/period bindings."),
        new("negation-attachment", "Explain why the alarm did not stop when the door opened. Do not suggest disabling it.",
            [@"Explain why the alarm did not stop when the door opened", @"Do not suggest disabling it"], [],
            [@"\b(how to stop|disable the alarm|door did not open|alarm stopped)\b"], [],
            "Task: Explain why the alarm did not stop when the door opened.\nConstraint: Do not suggest disabling it.",
            ["Task: Explain why the alarm stopped when the door did not open.\nConstraint: Do not suggest disabling it."],
            "Isolate the requested explanation and prohibition; never move negation to a different event."),
        new("ambiguous-pronoun", "Rewrite: Alex told Sam they were late. Preserve ambiguity.",
            [@"\bRewrite\b", @"Alex told Sam they were late", @"Preserve ambiguity"], [],
            [@"\b(Alex was late|Sam was late|both were late|he was late|she was late)\b"], [],
            "Task: Rewrite.\nSource: Alex told Sam they were late.\nConstraint: Preserve ambiguity.",
            ["Task: Rewrite.\nSource: Alex told Sam that Sam was late.\nConstraint: Preserve ambiguity."],
            "Separate source and instruction without choosing an antecedent."),
        new("unicode-and-quoted-code", "Explain `if (x != 2) return \"no\";` in 2 sentences. Keep the label \"船🚢\" exactly.",
            [@"\bExplain\b", @"\b2 sentences\b", @"Keep the label"], ["`if (x != 2) return \"no\";`", "\"船🚢\""],
            [@"\b(two sentences|Python|JavaScript|C\#|rename|translate)\b"], [],
            "Task: Explain `if (x != 2) return \"no\";`.\nOutput: 2 sentences.\nConstraint: Keep the label \"船🚢\" exactly.",
            ["Task: Explain `if (x == 2) return \"no\";`.\nOutput: 2 sentences.\nConstraint: Keep the label \"船🚢\" exactly."],
            "Separate exact code, output limit and Unicode label; neither infer a language nor alter a literal."),
        new("contradictory-counts", "Write exactly 2 sentences and exactly 3 sentences.",
            [@"exactly 2 sentences", @"exactly 3 sentences"], ["2", "3"], [], [], "",
            ["Task: Write exactly 2 sentences.\nFormat: concise."],
            "Do not resolve contradictory requirements without user clarification. Truthful refusal is safe but not a useful rewrite.", false)
    ];
}
